jenkins:
    build: jenkins
    volumes:
        - ./home:/var/jenkins_home
    environment:
        - SERVICE_NAME=SPACENAME-ci

git:
    build: git
    volumes:
        - /src
    command: 'true'

pg:
    image: postgres

slave:
    build: slave
    links:
        - pg
        - jenkins
    volumes:
        - ./slave:/home/slave
        - ./nginx/conf.d:/home/slave/nginx
    volumes_from:
        - git
        - nginx
    environment:
        - JAVA_HOME=/etc/alternatives/java_sdk
        - SERVICE_NAME=SPACENAME-omero
        - DOCKER_FIX='   '
    command: -labels java -labels slave -name slave -disableClientsUniqueId -executors 4

web:
    build: web
    ports:
        - "4080:4080"
    privileged: true
    links:
        - jenkins
        - redis
    volumes:
        - ./web:/home/omero
        - ./nginx/conf.d:/home/omero/nginx
    volumes_from:
        - nginx
    environment:
        - JENKINS_LABEL=/etc/alternatives/java_sdk
        - JENKINS_MODE=exclusive
        - SERVICE_NAME=SPACENAME-web

nginx:
    build: nginx
    ports:
        - "8888:80"
    privileged: true
    links:
        - jenkins
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./web/OMERO.server/lib/python/omeroweb/static:/home/omero/nginx/web/static
    environment:
        - JENKINS_LABEL=/etc/alternatives/java_sdk
        - JENKINS_MODE=exclusive
        - SERVICE_NAME=SPACENAME-nginx

redis:
    image: redis
    ports:
        - "6379:6379"
    environment:
        - SERVICE_NAME=SPACENAME-redis