jenkins:
    build: jenkins
    volumes:
        - ./home:/var/jenkins_home

git:
    build: git
    volumes:
        - /src
    command: 'true'

pg:
    image: postgres
    volumes:
        - ./pgdata:/var/lib/postgresql/data

testintegration:
    build: slave
    links:
        - pg
        - jenkins
        - seleniumhub
    volumes:
        - ./slave:/home/omero
    environment:
        - SLAVE_NAME=testintegration
        - SLAVE_EXECUTORS=4
        - SLAVE_PARAMS=-labels centos7 -labels ice36 -disableClientsUniqueId
    extra_hosts:
        - "testintegration:127.0.0.1"

omero:
    build: server
    links:
        - jenkins
        - pg
    volumes:
        - ./server:/home/omero
    environment:
        - SLAVE_NAME=omero
        - SLAVE_EXECUTORS=4
        - SLAVE_PARAMS=-labels centos7 -labels ice35 -disableClientsUniqueId

web:
    build: web
    links:
        - jenkins
        - redis
        - omero
        - testintegration
    volumes:
        - ./web:/home/omero
        - ./nginx/conf.d:/home/omero/nginx
    environment:
        - SLAVE_NAME=web
        - SLAVE_EXECUTORS=4
        - SLAVE_PARAMS= -labels centos7 -labels ice36 -disableClientsUniqueId

nginx:
    build: nginx
    links:
        - jenkins
        - web
    volumes:
        - ./nginx:/home/omero
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./web/static:/home/omero/static
    environment:
        - SLAVE_NAME=nginx
        - SLAVE_EXECUTORS=2
        - SLAVE_PARAMS=-labels centos7 -disableClientsUniqueId
    extra_hosts:
        - "webproxy:127.0.0.1"

redis:
    image: redis

seleniumhub:
    image: selenium/hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"
        - GRID_BROWSER_TIMEOUT=5000
        - GRID_TIMEOUT=5000
seleniumfirefox:
    image: selenium/node-firefox
    links:
        - seleniumhub:hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"
seleniumchrome:
    image: selenium/node-chrome
    links:
        - seleniumhub:hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"
